### ISSUE TITLE
the parser on yahoo finance does not work

### ISSUE THREAD

**Issue by AntonioBlago** [leonarduschen/pyfinmod#2]
Hello, thanks for this wonderful programm. Unfortuantly Yahoo updatet their webpage, so the parser cannot find anymore the table within the html.

**Comment by justinfriedman** [comment]
I am also getting an SSL error

**Comment by gustavorps** [comment]
Hi, you can use `pyfinmod.financials.Financials`

The lib get info from this website: https://financialmodelingprep.com/

```
from pyfinmod.financials import Financials
parser = Financials("AAPL")
parser.mktCap
```
